- name: Copying MongoDB
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo 
  
- name: Installing MongoDB
  ansible.builtin.package:
    name: mongodb-org
    state: present 

- name: Enabling and Starting MongoDB Server
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes

- name: Restarting MongoDB
  ansible.builtin.service:
    name: mongod
    state: restarted  

- name: setup root password
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ lookup('aws_ssm', '/roboshop/{{env}}/mysql_root_pass', region='us-east-1', decrypt=True ) }}"