- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: phyton setup
  ansible.builtin.import_role:
    name: common
    tasks_from: phyton

- name: system start
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd 