- name: stop {{component}}
  tags:
  - deployment
  ansible.builtin.service:
    name: "{{component}}"
    state: stopped

- name: Recursively remove app directory
  tags:
  - deployment
  ansible.builtin.file:
    path: /app
    state: absent
    force: yes 
    #recurse: yes #to remove directory 

- name: Creating Directory called App
  tags:
  - deployment
  ansible.builtin.file:
    path: /app
    state: directory

- name: Donload Catalogue Application
  tags:
  - deployment
  ansible.builtin.get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{component}}.zip"
    dest: /tmp

- name: Extracting Catalogue Application
  tags:
  - deployment
  ansible.builtin.unarchive: 
    src: "/tmp/{{component}}.zip"
    dest: /app
    remote_src: yes #if file is alredy in remote source

- name: Installing nmp Dependecies
  tags:
  - deployment
  ansible.builtin.command: npm install
  args: #args can be used to change directory
    chdir: /app

- name: restart "{{component}}"
  tags:
  - deployment
  ansible.builtin.service:
    name: "{{component}}"
    state: restart